galaxy_info:
  author: Adrian Estrada
  description: Generates RDP files and launchers for different cloud platforms.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: CentOS
      versions:
        - all
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - rdp
    - winrm
